# Generated by Django 2.0.7 on 2019-12-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191217_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
