# Generated by Django 2.0.7 on 2019-12-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191222_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='work',
            field=models.CharField(default='单双排', max_length=100),
        ),
    ]
