# Generated by Django 2.0.7 on 2019-12-24 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20191224_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='down_user',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='down_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
