# Generated by Django 2.0.7 on 2019-12-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_recharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='trade_no',
            field=models.CharField(max_length=64, null=True, verbose_name='流水号'),
        ),
    ]
