# Generated by Django 2.0.7 on 2019-12-26 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20191225_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='视频名称')),
                ('intro', models.CharField(max_length=255, verbose_name='视频简介')),
                ('direction', models.CharField(max_length=255, verbose_name='视频路径')),
                ('order', models.IntegerField(default=0, verbose_name='展示顺序')),
                ('image', models.ImageField(upload_to='movie_img', verbose_name='视频图片')),
                ('like', models.IntegerField(verbose_name='点赞数')),
                ('collections_num', models.IntegerField(verbose_name='收藏数')),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='视频拥有者')),
            ],
        ),
    ]
