# Generated by Django 2.0.7 on 2019-12-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='daidai_banner',
        ),
    ]
